-- 1. Create the assignments table
create table if not exists public.collector_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ruas_jalan text not null,
  created_at timestamptz default now(),
  unique(user_id, ruas_jalan) -- Prevent duplicate assignments
);

-- 2. Enable RLS
alter table public.collector_assignments enable row level security;

-- 3. Policies
-- Admin: Full Access
create policy "Admins can do everything on assignments"
  on public.collector_assignments
  for all
  using (
    exists (
      select 1 from profiles 
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Collector: View Only (Own Assignments)
create policy "Collectors can view own assignments"
  on public.collector_assignments
  for select
  using (
    auth.uid() = user_id
  );
