
-- 1. Create the Master Data Table
create table if not exists public.parking_points (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  location_name text not null,
  street_name text, -- Added for Ruas Jalan categorization
  jukir_name text not null,
  shift text not null check (shift in ('Pagi', 'Malam')),
  target_amount numeric default 0,
  is_active boolean default true
);

-- 2. Enable Row Level Security
alter table public.parking_points enable row level security;

-- 3. RLS Policies

-- Policy A: Authenticated users (Collectors & Admins) can VIEW (Select)
create policy "Authenticated users can view parking points"
  on public.parking_points
  for select
  to authenticated
  using ( true );

-- Policy B: Only Admins can INSERT, UPDATE, DELETE
create policy "Admins can manage parking points"
  on public.parking_points
  for all
  using (
    exists (
      select 1 from profiles 
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
