-- Function 1: Get all unique street names from both shifts
create or replace function get_all_ruas_jalan()
returns table (ruas_jalan text)
language plpgsql
as $$
begin
  return query
    select distinct "Ruas Jalan" from "DataPagi"
    where "Ruas Jalan" is not null
    union
    select distinct "Ruas Jalan" from "DataMalam"
    where "Ruas Jalan" is not null
    order by 1 asc;
end;
$$;

-- Function 2: Get Jukir list based on street and shift
create or replace function get_jukir_by_ruas_jalan(target_jalan text, filter_shift text)
returns table (
  id bigint,
  nama_jukir text,
  lokasi_parkir text,
  jenis_shift text
)
language plpgsql
as $$
begin
  if filter_shift = 'Pagi' then
    return query
      select 
        d.id, 
        d."Nama Jukir" as nama_jukir, 
        coalesce(d."Titik Parkir", '-') as lokasi_parkir,
        'Pagi'::text as jenis_shift
      from "DataPagi" d
      where upper(trim(d."Ruas Jalan")) = upper(trim(target_jalan));
  else
    return query
      select 
        d.id, 
        d."Nama Jukir" as nama_jukir, 
        coalesce(d."Titik Parkir", '-') as lokasi_parkir,
        'Malam'::text as jenis_shift
      from "DataMalam" d
      where upper(trim(d."Ruas Jalan")) = upper(trim(target_jalan));
  end if;
end;
$$;

-- Optional: Create a transactions table if it doesn't exist
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  jukir_id bigint not null,
  jukir_name text not null,
  shift text not null,
  amount numeric not null,
  street_name text,
  image_path text
);
